# Generated by Django 6.0.3 on 2026-04-23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=240)),
                ("excerpt", models.TextField()),
                ("category", models.CharField(max_length=64)),
                ("read_time_minutes", models.PositiveSmallIntegerField(default=5)),
                ("published_at", models.DateField(default=django.utils.timezone.localdate)),
                ("author", models.CharField(max_length=140)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("image_query", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                ("audio_url", models.URLField(blank=True)),
                ("audio_duration_sec", models.PositiveIntegerField(blank=True, null=True)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-published_at", "rank", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Brief",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=240)),
                ("summary", models.TextField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=10)),
                ("published_at", models.DateField(default=django.utils.timezone.localdate)),
                ("category", models.CharField(default="Daily Brief", max_length=64)),
                ("image_url", models.URLField(blank=True)),
                ("audio_url", models.URLField(blank=True)),
                ("insights", models.PositiveSmallIntegerField(default=0)),
                ("rank", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-published_at", "rank", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCollection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#6366f1", max_length=16)),
                ("icon", models.CharField(default="folder", max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mobile_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserEntitlement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("lifetime", "Lifetime"),
                        ],
                        default="free",
                        max_length=16,
                    ),
                ),
                ("qa_override_enabled", models.BooleanField(default=False)),
                (
                    "qa_override_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("lifetime", "Lifetime"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserReadingEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("read_time_ms", models.PositiveIntegerField(default=0)),
                ("event_date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reading_events",
                        to="mobileapi.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSavedArticle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="mobileapi.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCollectionArticle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="mobileapi.article",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="mobileapi.usercollection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="usersavedarticle",
            constraint=models.UniqueConstraint(
                fields=("user", "article"),
                name="mobileapi_saved_user_article_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercollectionarticle",
            constraint=models.UniqueConstraint(
                fields=("collection", "article"),
                name="mobileapi_collection_article_unique",
            ),
        ),
    ]
