# Generated by Django 6.0.2 on 2026-05-24 15:59

import django.db.models.deletion
from django.db import migrations, models

def migrate_category_strings_to_fk(apps, schema_editor):
    Article = apps.get_model('mobileapi', 'Article')
    Category = apps.get_model('mobileapi', 'Category')
    
    for article in Article.objects.all():
        old_cat_name = article.category_old
        if old_cat_name:
            # Try to find a matching Category by name or slug case-insensitively
            category = Category.objects.filter(
                models.Q(name__iexact=old_cat_name) | models.Q(slug__iexact=old_cat_name)
            ).first()
            
            if not category:
                # Fallback to create it if it doesn't exist
                from django.utils.text import slugify
                slug = slugify(old_cat_name)[:32]
                category, _ = Category.objects.get_or_create(
                    slug=slug,
                    defaults={
                        'name': old_cat_name,
                        'color': '#64748b',
                        'icon': 'layers',
                        'rank': 99
                    }
                )
            
            article.category = category
            article.save(update_fields=['category'])

def noop_reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0004_userentitlement_revenuecat_customer_id_and_more'),
    ]

    operations = [
        # 1. Rename 'category' field to 'category_old'
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='category_old',
        ),
        # 2. Add 'category' ForeignKey field as nullable initially
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='articles',
                to='mobileapi.category'
            ),
        ),
        # 3. Populate 'category' FK based on 'category_old'
        migrations.RunPython(migrate_category_strings_to_fk, noop_reverse),
        # 4. Make 'category' FK non-nullable
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='articles',
                to='mobileapi.category'
            ),
        ),
        # 5. Remove 'category_old' field
        migrations.RemoveField(
            model_name='article',
            name='category_old',
        ),
    ]
