# Generated by Django 6.0.3 on 2026-05-31 16:35

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0005_alter_article_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=280, unique=True),
        ),
        migrations.AlterField(
            model_name='userreadingevent',
            name='event_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at', 'rank', 'id'], name='article_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='userreadingevent',
            index=models.Index(fields=['user', '-created_at'], name='reading_event_user_idx'),
        ),
    ]
