# Generated by Django 6.0.2 on 2026-06-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0007_clear_demo_audio_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='published', max_length=16),
        ),
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
