# Generated by Django 6.0.2 on 2026-06-09 18:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0008_article_source_links_article_status_article_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_article_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ArticleEmbedding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='mobileapi.article')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
