# Generated by Django 6.0.2 on 2026-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0010_article_fts_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentitlement',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userentitlement',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
