# Generated by Django 6.0.2 on 2026-06-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0011_userentitlement_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='web_push_subscription',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
