# Generated by Django 6.0.2 on 2026-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapi', '0012_userdevice_web_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentitlement',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='userentitlement',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
