# Generated by Django 6.0.2 on 2026-06-09 18:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobileapi', '0008_article_source_links_article_status_article_topics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('rss', 'RSS / Atom feed'), ('api', 'News API')], default='rss', max_length=16)),
                ('url', models.URLField(max_length=500)),
                ('homepage_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('fetch_interval_minutes', models.PositiveSmallIntegerField(default=60)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, help_text='Default category hint for stories from this source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_sources', to='mobileapi.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoryCluster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('open', 'Open'), ('drafted', 'Drafted'), ('discarded', 'Discarded')], db_index=True, default='open', max_length=16)),
                ('is_breaking', models.BooleanField(default=False)),
                ('drafted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_clusters', to='mobileapi.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=240)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('dedup_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('clustered', 'Clustered'), ('discarded', 'Discarded')], db_index=True, default='new', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', to='content_pipeline.source')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='content_pipeline.storycluster')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='rawitem_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('article', 'Article'), ('brief', 'Brief')], default='article', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='in_review', max_length=16)),
                ('title', models.CharField(max_length=240)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('author', models.CharField(default='Curator Editorial', max_length=140)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=5)),
                ('image_query', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('source_links', models.JSONField(blank=True, default=list)),
                ('is_breaking', models.BooleanField(default=False)),
                ('llm_model', models.CharField(blank=True, max_length=64)),
                ('review_notes', models.TextField(blank=True)),
                ('scheduled_publish_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_drafts', to='mobileapi.category')),
                ('published_article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_draft', to='mobileapi.article')),
                ('published_brief', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_draft', to='mobileapi.brief')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_drafts', to=settings.AUTH_USER_MODEL)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='content_pipeline.storycluster')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='draft_status_idx')],
            },
        ),
    ]
