# Generated by Django 6.0.2 on 2026-06-13 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchNotifySignup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('source', models.CharField(blank=True, default='launch_site', max_length=64)),
            ],
            options={
                'verbose_name': 'launch notify signup',
                'verbose_name_plural': 'launch notify signups',
                'ordering': ['-created_at'],
            },
        ),
    ]
