from django.urls import path

from mobileapi.views import (
    ArticleAudioView,
    ArticleDetailView,
    ArticleListView,
    BriefAudioView,
    BriefListView,
    CategoryListView,
    CollectionArticleView,
    CollectionDetailView,
    CollectionListView,
    DeviceCollectionView,
    DeviceDetailView,
    EntitlementQAOverrideView,
    EntitlementView,
    FeedbackCreateView,
    PreferenceView,
    PrivacyExportListView,
    PrivacyExportRequestView,
    ReadingEventView,
    ReadingStatsView,
    SavedArticleCollectionView,
    SavedArticleDetailView,
    PrivacyExportDownloadView,
    PublicAudioFileView,
    RevenueCatWebhookView,
)

app_name = "mobileapi"

urlpatterns = [
    path("categories", CategoryListView.as_view(), name="categories"),
    path("articles", ArticleListView.as_view(), name="articles"),
    path("articles/<uuid:article_id>", ArticleDetailView.as_view(), name="article-detail"),
    path("articles/<uuid:article_id>/audio", ArticleAudioView.as_view(), name="article-audio"),
    path("briefs", BriefListView.as_view(), name="briefs"),
    path("briefs/<uuid:brief_id>/audio", BriefAudioView.as_view(), name="brief-audio"),
    path("media/audio/<path:storage_path>", PublicAudioFileView.as_view(), name="public-audio-file"),
    path("preferences", PreferenceView.as_view(), name="preferences"),
    path("devices", DeviceCollectionView.as_view(), name="devices"),
    path("devices/<uuid:device_id>", DeviceDetailView.as_view(), name="device-detail"),
    path("saves", SavedArticleCollectionView.as_view(), name="saves"),
    path("saves/<uuid:article_id>", SavedArticleDetailView.as_view(), name="save-detail"),
    path("collections", CollectionListView.as_view(), name="collections"),
    path("collections/<uuid:collection_id>", CollectionDetailView.as_view(), name="collection-detail"),
    path(
        "collections/<uuid:collection_id>/articles",
        CollectionArticleView.as_view(),
        name="collection-articles",
    ),
    path(
        "collections/<uuid:collection_id>/articles/<uuid:article_id>",
        CollectionArticleView.as_view(),
        name="collection-article-detail",
    ),
    path("reading/stats", ReadingStatsView.as_view(), name="reading-stats"),
    path("reading/events", ReadingEventView.as_view(), name="reading-events"),
    path("feedback", FeedbackCreateView.as_view(), name="feedback"),
    path("privacy/export", PrivacyExportRequestView.as_view(), name="privacy-export"),
    path("privacy/exports", PrivacyExportListView.as_view(), name="privacy-exports"),
    path("entitlements", EntitlementView.as_view(), name="entitlements"),
    path(
        "entitlements/qa-override",
        EntitlementQAOverrideView.as_view(),
        name="entitlements-qa-override",
    ),
    path("privacy/exports/<uuid:export_id>/download", PrivacyExportDownloadView.as_view(), name="privacy-export-download"),
    path("webhooks/revenuecat", RevenueCatWebhookView.as_view(), name="revenuecat-webhook"),
]
