# Generated by Django 6.0.3 on 2026-04-03 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategoryPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_key', models.CharField(choices=[('world', 'World'), ('business', 'Business'), ('technology', 'Technology'), ('science', 'Science'), ('culture', 'Culture'), ('design', 'Design'), ('climate', 'Climate'), ('policy', 'Policy'), ('sport', 'Sport')], max_length=32)),
            ],
            options={
                'ordering': ['category_key'],
            },
        ),
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.CharField(choices=[('account', 'Account'), ('categories', 'Categories'), ('appearance', 'Appearance'), ('notifications', 'Notifications'), ('reading', 'Reading'), ('complete', 'Complete')], default='account', max_length=32)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=16)),
                ('notification_frequency', models.CharField(choices=[('daily', 'Daily'), ('breaking', 'Breaking'), ('weekly', 'Weekly'), ('none', 'None')], default='daily', max_length=16)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_digest_enabled', models.BooleanField(default=True)),
                ('auto_save_enabled', models.BooleanField(default=True)),
                ('text_size', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable'), ('large', 'Large')], default='comfortable', max_length=16)),
                ('reduce_motion_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
