# Generated by Django 6.0.3 on 2026-05-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategorypreference',
            name='category_key',
            field=models.CharField(choices=[('economy', 'Economy'), ('technology', 'Technology'), ('science', 'Science'), ('culture', 'Culture'), ('health', 'Health'), ('politics', 'Politics'), ('climate', 'Climate')], max_length=32),
        ),
    ]
