# Generated by Django 6.0.2 on 2026-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_usercategorypreference_category_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategorypreference',
            name='category_key',
            field=models.CharField(choices=[('news', 'World News'), ('economy', 'Economy'), ('technology', 'Technology'), ('climate', 'Climate'), ('culture', 'Culture'), ('health', 'Health'), ('politics', 'Politics'), ('science', 'Science')], max_length=32),
        ),
    ]
