// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/category/:slug": {
    params: {
      "slug": string;
    };
  };
  "/briefs": {
    params: {};
  };
  "/article/:slugOrId": {
    params: {
      "slugOrId": string;
    };
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/account-deletion": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/news-sitemap.xml": {
    params: {};
  };
  "/rss.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/welcome": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/home": {
    params: {};
  };
  "/brief": {
    params: {};
  };
  "/explore": {
    params: {};
  };
  "/saved": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/reading-stats": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/menu": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/donate": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/help": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/collection/:id": {
    params: {
      "id": string;
    };
  };
  "/language-region": {
    params: {};
  };
  "/connected-accounts": {
    params: {};
  };
  "/data-export": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/category/:slug" | "/briefs" | "/article/:slugOrId" | "/privacy" | "/terms" | "/support" | "/account-deletion" | "/sitemap.xml" | "/news-sitemap.xml" | "/rss.xml" | "/robots.txt" | "/welcome" | "/sign-in" | "/sign-up" | "/onboarding" | "/forgot-password" | "/reset-password" | "/auth/callback" | "/home" | "/brief" | "/explore" | "/saved" | "/search" | "/reading-stats" | "/settings" | "/account" | "/menu" | "/profile" | "/donate" | "/about" | "/help" | "/collections" | "/collection/:id" | "/language-region" | "/connected-accounts" | "/data-export" | "/*";
  };
  "routes/public/home.tsx": {
    id: "routes/public/home";
    page: "/";
  };
  "routes/public/layout.tsx": {
    id: "routes/public/layout";
    page: "/category/:slug" | "/briefs";
  };
  "routes/public/category.tsx": {
    id: "routes/public/category";
    page: "/category/:slug";
  };
  "routes/public/briefs.tsx": {
    id: "routes/public/briefs";
    page: "/briefs";
  };
  "routes/article.tsx": {
    id: "routes/article";
    page: "/article/:slugOrId";
  };
  "routes/public/privacy.tsx": {
    id: "routes/public/privacy";
    page: "/privacy";
  };
  "routes/public/terms.tsx": {
    id: "routes/public/terms";
    page: "/terms";
  };
  "routes/public/support.tsx": {
    id: "routes/public/support";
    page: "/support";
  };
  "routes/public/account-deletion.tsx": {
    id: "routes/public/account-deletion";
    page: "/account-deletion";
  };
  "routes/seo/sitemap.ts": {
    id: "routes/seo/sitemap";
    page: "/sitemap.xml";
  };
  "routes/seo/news-sitemap.ts": {
    id: "routes/seo/news-sitemap";
    page: "/news-sitemap.xml";
  };
  "routes/seo/rss.ts": {
    id: "routes/seo/rss";
    page: "/rss.xml";
  };
  "routes/seo/robots.ts": {
    id: "routes/seo/robots";
    page: "/robots.txt";
  };
  "routes/app/layout.tsx": {
    id: "routes/app/layout";
    page: "/welcome" | "/sign-in" | "/sign-up" | "/onboarding" | "/forgot-password" | "/reset-password" | "/auth/callback" | "/home" | "/brief" | "/explore" | "/saved" | "/search" | "/reading-stats" | "/settings" | "/account" | "/menu" | "/profile" | "/donate" | "/about" | "/help" | "/collections" | "/collection/:id" | "/language-region" | "/connected-accounts" | "/data-export";
  };
  "routes/app/welcome.tsx": {
    id: "routes/app/welcome";
    page: "/welcome";
  };
  "routes/app/sign-in.tsx": {
    id: "routes/app/sign-in";
    page: "/sign-in";
  };
  "routes/app/sign-up.tsx": {
    id: "routes/app/sign-up";
    page: "/sign-up";
  };
  "routes/app/onboarding.tsx": {
    id: "routes/app/onboarding";
    page: "/onboarding";
  };
  "routes/app/forgot-password.tsx": {
    id: "routes/app/forgot-password";
    page: "/forgot-password";
  };
  "routes/app/reset-password.tsx": {
    id: "routes/app/reset-password";
    page: "/reset-password";
  };
  "routes/app/auth-callback.tsx": {
    id: "routes/app/auth-callback";
    page: "/auth/callback";
  };
  "routes/app/home.tsx": {
    id: "routes/app/home";
    page: "/home";
  };
  "routes/app/brief.tsx": {
    id: "routes/app/brief";
    page: "/brief";
  };
  "routes/app/explore.tsx": {
    id: "routes/app/explore";
    page: "/explore";
  };
  "routes/app/saved.tsx": {
    id: "routes/app/saved";
    page: "/saved";
  };
  "routes/app/search.tsx": {
    id: "routes/app/search";
    page: "/search";
  };
  "routes/app/reading-stats.tsx": {
    id: "routes/app/reading-stats";
    page: "/reading-stats";
  };
  "routes/app/settings.tsx": {
    id: "routes/app/settings";
    page: "/settings";
  };
  "routes/app/account.tsx": {
    id: "routes/app/account";
    page: "/account";
  };
  "routes/app/menu.tsx": {
    id: "routes/app/menu";
    page: "/menu";
  };
  "routes/app/profile.tsx": {
    id: "routes/app/profile";
    page: "/profile";
  };
  "routes/app/donate.tsx": {
    id: "routes/app/donate";
    page: "/donate";
  };
  "routes/app/about.tsx": {
    id: "routes/app/about";
    page: "/about";
  };
  "routes/app/help.tsx": {
    id: "routes/app/help";
    page: "/help";
  };
  "routes/app/collections.tsx": {
    id: "routes/app/collections";
    page: "/collections";
  };
  "routes/app/collection-detail.tsx": {
    id: "routes/app/collection-detail";
    page: "/collection/:id";
  };
  "routes/app/language-region.tsx": {
    id: "routes/app/language-region";
    page: "/language-region";
  };
  "routes/app/connected-accounts.tsx": {
    id: "routes/app/connected-accounts";
    page: "/connected-accounts";
  };
  "routes/app/data-export.tsx": {
    id: "routes/app/data-export";
    page: "/data-export";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/public/home": typeof import("./src/routes/public/home.tsx");
  "routes/public/layout": typeof import("./src/routes/public/layout.tsx");
  "routes/public/category": typeof import("./src/routes/public/category.tsx");
  "routes/public/briefs": typeof import("./src/routes/public/briefs.tsx");
  "routes/article": typeof import("./src/routes/article.tsx");
  "routes/public/privacy": typeof import("./src/routes/public/privacy.tsx");
  "routes/public/terms": typeof import("./src/routes/public/terms.tsx");
  "routes/public/support": typeof import("./src/routes/public/support.tsx");
  "routes/public/account-deletion": typeof import("./src/routes/public/account-deletion.tsx");
  "routes/seo/sitemap": typeof import("./src/routes/seo/sitemap.ts");
  "routes/seo/news-sitemap": typeof import("./src/routes/seo/news-sitemap.ts");
  "routes/seo/rss": typeof import("./src/routes/seo/rss.ts");
  "routes/seo/robots": typeof import("./src/routes/seo/robots.ts");
  "routes/app/layout": typeof import("./src/routes/app/layout.tsx");
  "routes/app/welcome": typeof import("./src/routes/app/welcome.tsx");
  "routes/app/sign-in": typeof import("./src/routes/app/sign-in.tsx");
  "routes/app/sign-up": typeof import("./src/routes/app/sign-up.tsx");
  "routes/app/onboarding": typeof import("./src/routes/app/onboarding.tsx");
  "routes/app/forgot-password": typeof import("./src/routes/app/forgot-password.tsx");
  "routes/app/reset-password": typeof import("./src/routes/app/reset-password.tsx");
  "routes/app/auth-callback": typeof import("./src/routes/app/auth-callback.tsx");
  "routes/app/home": typeof import("./src/routes/app/home.tsx");
  "routes/app/brief": typeof import("./src/routes/app/brief.tsx");
  "routes/app/explore": typeof import("./src/routes/app/explore.tsx");
  "routes/app/saved": typeof import("./src/routes/app/saved.tsx");
  "routes/app/search": typeof import("./src/routes/app/search.tsx");
  "routes/app/reading-stats": typeof import("./src/routes/app/reading-stats.tsx");
  "routes/app/settings": typeof import("./src/routes/app/settings.tsx");
  "routes/app/account": typeof import("./src/routes/app/account.tsx");
  "routes/app/menu": typeof import("./src/routes/app/menu.tsx");
  "routes/app/profile": typeof import("./src/routes/app/profile.tsx");
  "routes/app/donate": typeof import("./src/routes/app/donate.tsx");
  "routes/app/about": typeof import("./src/routes/app/about.tsx");
  "routes/app/help": typeof import("./src/routes/app/help.tsx");
  "routes/app/collections": typeof import("./src/routes/app/collections.tsx");
  "routes/app/collection-detail": typeof import("./src/routes/app/collection-detail.tsx");
  "routes/app/language-region": typeof import("./src/routes/app/language-region.tsx");
  "routes/app/connected-accounts": typeof import("./src/routes/app/connected-accounts.tsx");
  "routes/app/data-export": typeof import("./src/routes/app/data-export.tsx");
  "routes/not-found": typeof import("./src/routes/not-found.tsx");
};